addons:
  postgresql: 9.3

env:
  - DB=mysql
  - DB=postgres
  - DB=postgres-native
  - DB=sqlite

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database sqlalchemy_continuum_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres-native' ]; then psql -c 'create database sqlalchemy_continuum_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database sqlalchemy_continuum_test;'; fi"

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -e  ".[test]"
script:
  - py.test
